## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'holoeye'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_holoeye' #to modify
description = 'Set of PyMoDAQ plugins for Holoeye Spatial Light Modulator (SLM)'

author = 'Sébastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0']
##